//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.13 at 08:13:34 AM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "MDA_Common_Types")

package org.kephis.ecs_kesws.xml.parser.i.ogcdsubi.v_1_0.mda_common_types;
