//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.22 at 04:22:38 PM EAT 
//


package org.kephis.ecs_kesws.xml.parser.i.ogpayres.v_1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DocumentDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="consignment_refnumber" type="{}ApplnRefNoType"/&gt;
 *         &lt;element name="ver_no" type="{}VersionNoType"/&gt;
 *         &lt;element name="transaction_number" type="{}TransRefNoType"/&gt;
 *         &lt;element name="bank_code" type="{}BankCodeType" minOccurs="0"/&gt;
 *         &lt;element name="branch_code" type="{}BranchCodeType" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{}StatusCodeType"/&gt;
 *         &lt;element name="prepayment_account" type="{}PrePaymentAcctType" minOccurs="0"/&gt;
 *         &lt;element name="payment_date" type="{}TimeStampType"/&gt;
 *         &lt;element name="amount" type="{}AmountType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentDetailsType", propOrder = {
    "consignmentRefnumber",
    "verNo",
    "transactionNumber",
    "bankCode",
    "branchCode",
    "status",
    "prepaymentAccount",
    "paymentDate",
    "amount"
})
public class DocumentDetailsType {

    @XmlElement(name = "consignment_refnumber", required = true)
    protected String consignmentRefnumber;
    @XmlElement(name = "ver_no", required = true)
    protected String verNo;
    @XmlElement(name = "transaction_number", required = true)
    protected String transactionNumber;
    @XmlElement(name = "bank_code")
    protected String bankCode;
    @XmlElement(name = "branch_code")
    protected String branchCode;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "prepayment_account")
    protected String prepaymentAccount;
    @XmlElement(name = "payment_date", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String paymentDate;
    @XmlElement(required = true)
    protected BigDecimal amount;

    /**
     * Gets the value of the consignmentRefnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsignmentRefnumber() {
        return consignmentRefnumber;
    }

    /**
     * Sets the value of the consignmentRefnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsignmentRefnumber(String value) {
        this.consignmentRefnumber = value;
    }

    /**
     * Gets the value of the verNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerNo() {
        return verNo;
    }

    /**
     * Sets the value of the verNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerNo(String value) {
        this.verNo = value;
    }

    /**
     * Gets the value of the transactionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionNumber() {
        return transactionNumber;
    }

    /**
     * Sets the value of the transactionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionNumber(String value) {
        this.transactionNumber = value;
    }

    /**
     * Gets the value of the bankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * Sets the value of the bankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode(String value) {
        this.bankCode = value;
    }

    /**
     * Gets the value of the branchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the prepaymentAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrepaymentAccount() {
        return prepaymentAccount;
    }

    /**
     * Sets the value of the prepaymentAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrepaymentAccount(String value) {
        this.prepaymentAccount = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDate(String value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

}
