//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.15 at 12:17:31 PM EAT 
//


package org.kephis.ecs_kesws.xml.parser.o.ogcdres.v_1_1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductDetailsType }
     * 
     */
  

    /**
     * Create an instance of {@link ConsignmentDocument }
     * 
     */
    public ConsignmentDocument createConsignmentDocument() {
        return new ConsignmentDocument();
    }

    /**
     * Create an instance of {@link DocumentDetailsType }
     * 
     */
    public DocumentDetailsType createDocumentDetailsType() {
        return new DocumentDetailsType();
    }

    /**
     * Create an instance of {@link KEPHISHeaderFieldsType }
     * 
     */
    public KEPHISHeaderFieldsType createKEPHISHeaderFieldsType() {
        return new KEPHISHeaderFieldsType();
    }

    /**
     * Create an instance of {@link ActionDetailsType }
     * 
     */
    public ActionDetailsType createActionDetailsType() {
        return new ActionDetailsType();
    }

    /**
     * Create an instance of {@link ItemCommodityDetailsType }
     * 
     */
    public ItemCommodityDetailsType createItemCommodityDetailsType() {
        return new ItemCommodityDetailsType();
    }

    /**
     * Create an instance of {@link CDRiskDetailsType }
     * 
     */
    public CDRiskDetailsType createCDRiskDetailsType() {
        return new CDRiskDetailsType();
    }

    /**
     * Create an instance of {@link ApprovalDetailsType }
     * 
     */
    public ApprovalDetailsType createApprovalDetailsType() {
        return new ApprovalDetailsType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link ConsignmentDocDetailsType }
     * 
     */
 

    /**
     * Create an instance of {@link RiskAssessmentType }
     * 
     */
    public RiskAssessmentType createRiskAssessmentType() {
        return new RiskAssessmentType();
    }

    /**
     * Create an instance of {@link ProductDetailsType.ItemDetails }
     * 
     */
  

}
