//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.15 at 12:17:31 PM EAT 
//


package org.kephis.ecs_kesws.xml.parser.o.ogcdres.v_1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RiskAssessmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RiskAssessmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileCode" type="{MDA_Common_Types}ProfileCodeType"/>
 *         &lt;element name="ProfileName" type="{MDA_Common_Types}ProfileNameType"/>
 *         &lt;element name="AssessedLane" type="{MDA_Common_Types}AssessedLaneType"/>
 *         &lt;element name="AssesedDate" type="{}DateTimeFormatType"/>
 *         &lt;element name="ActionDetails" type="{}ActionDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RiskAssessmentType", propOrder = {
    "profileCode",
    "profileName",
    "assessedLane",
    "assesedDate",
    "actionDetails"
})
public class RiskAssessmentType {

    @XmlElement(name = "ProfileCode", required = true)
    protected String profileCode;
    @XmlElement(name = "ProfileName", required = true)
    protected String profileName;
    @XmlElement(name = "AssessedLane", required = true)
    protected String assessedLane;
    @XmlElement(name = "AssesedDate", required = true)
    protected String assesedDate;
    @XmlElement(name = "ActionDetails")
    protected ActionDetailsType actionDetails;

    /**
     * Gets the value of the profileCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileCode() {
        return profileCode;
    }

    /**
     * Sets the value of the profileCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileCode(String value) {
        this.profileCode = value;
    }

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the assessedLane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessedLane() {
        return assessedLane;
    }

    /**
     * Sets the value of the assessedLane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessedLane(String value) {
        this.assessedLane = value;
    }

    /**
     * Gets the value of the assesedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssesedDate() {
        return assesedDate;
    }

    /**
     * Sets the value of the assesedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssesedDate(String value) {
        this.assesedDate = value;
    }

    /**
     * Gets the value of the actionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ActionDetailsType }
     *     
     */
    public ActionDetailsType getActionDetails() {
        return actionDetails;
    }

    /**
     * Sets the value of the actionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionDetailsType }
     *     
     */
    public void setActionDetails(ActionDetailsType value) {
        this.actionDetails = value;
    }

}
