//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.29 at 06:08:07 PM EAT 
//


package org.kephis.ecs_kesws.xml.parser.i.ogerrorres.v_1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}document_reference_no"/>
 *         &lt;element ref="{}doc_ver_number"/>
 *         &lt;element ref="{}file_name" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentReferenceNo",
    "docVerNumber",
    "fileName"
})
@XmlRootElement(name = "document_details")
public class DocumentDetails {

    @XmlElement(name = "document_reference_no", required = true)
    protected String documentReferenceNo;
    @XmlElement(name = "doc_ver_number", required = true)
    protected String docVerNumber;
    @XmlElement(name = "file_name")
    protected String fileName;

    /**
     * Gets the value of the documentReferenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentReferenceNo() {
        return documentReferenceNo;
    }

    /**
     * Sets the value of the documentReferenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentReferenceNo(String value) {
        this.documentReferenceNo = value;
    }

    /**
     * Gets the value of the docVerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocVerNumber() {
        return docVerNumber;
    }

    /**
     * Sets the value of the docVerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocVerNumber(String value) {
        this.docVerNumber = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

}
