//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.29 at 06:08:07 PM EAT 
//


package org.kephis.ecs_kesws.xml.parser.i.ogerrorres.v_1_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}msghdr"/>
 *         &lt;element ref="{}document_details" maxOccurs="unbounded"/>
 *         &lt;element ref="{}errorInformation" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msghdr",
    "documentDetails",
    "errorInformation"
})
@XmlRootElement(name = "keswsresponse")
public class ErrorResponse {

    @XmlElement(required = true)
    protected Msghdr msghdr;
    @XmlElement(name = "document_details", required = true)
    protected List<DocumentDetails> documentDetails;
    @XmlElement(required = true)
    protected List<ErrorInformation> errorInformation;

    /**
     * Gets the value of the msghdr property.
     * 
     * @return
     *     possible object is
     *     {@link Msghdr }
     *     
     */
    public Msghdr getMsghdr() {
        return msghdr;
    }

    /**
     * Sets the value of the msghdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msghdr }
     *     
     */
    public void setMsghdr(Msghdr value) {
        this.msghdr = value;
    }

    /**
     * Gets the value of the documentDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentDetails }
     * 
     * 
     */
    public List<DocumentDetails> getDocumentDetails() {
        if (documentDetails == null) {
            documentDetails = new ArrayList<DocumentDetails>();
        }
        return this.documentDetails;
    }

    /**
     * Gets the value of the errorInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorInformation }
     * 
     * 
     */
    public List<ErrorInformation> getErrorInformation() {
        if (errorInformation == null) {
            errorInformation = new ArrayList<ErrorInformation>();
        }
        return this.errorInformation;
    }

}
